[[constraint]]
  name = "github.com/go-cmd/cmd"
  version = "~1.0"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
